/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Calculation;
import static java.lang.System.out;
import java.text.DecimalFormat;

/**
 *
 * @author gomen
 */
public class Calculators extends javax.swing.JFrame {

    private boolean actionTest;
    private double previousVal;
    private double currentVal;
    DecimalFormat decFormat;

    
    /**
     * Creates new form Calculators
     */
    public Calculators() {
        decFormat = new DecimalFormat("#,##0");
        decFormat.setMaximumFractionDigits(10);
        initComponents();
        setActionTest(false);
        setCurrentVal(0);
        setPreviousVal(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        but_numOne = new javax.swing.JButton();
        but_numZero = new javax.swing.JButton();
        but_actPlus = new javax.swing.JButton();
        but_numFive = new javax.swing.JButton();
        but_numSix = new javax.swing.JButton();
        txt_areaDisplay = new javax.swing.JTextField();
        but_numTwo = new javax.swing.JButton();
        txt_numDisplay = new javax.swing.JTextField();
        but_numThree = new javax.swing.JButton();
        but_numDecimal = new javax.swing.JButton();
        but_actPosNeg = new javax.swing.JButton();
        but_numSeven = new javax.swing.JButton();
        but_numEight = new javax.swing.JButton();
        but_numNine = new javax.swing.JButton();
        but_actDivide = new javax.swing.JButton();
        but_actMultiply = new javax.swing.JButton();
        but_actMinus = new javax.swing.JButton();
        but_actClear = new javax.swing.JButton();
        but_numFour = new javax.swing.JButton();
        but_actEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        but_numOne.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numOne.setText("1");
        but_numOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numOneActionPerformed(evt);
            }
        });

        but_numZero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numZero.setText("0");
        but_numZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numZeroActionPerformed(evt);
            }
        });

        but_actPlus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_actPlus.setText("+");
        but_actPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_actPlusActionPerformed(evt);
            }
        });

        but_numFive.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numFive.setText("5");
        but_numFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numFiveActionPerformed(evt);
            }
        });

        but_numSix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numSix.setText("6");
        but_numSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numSixActionPerformed(evt);
            }
        });

        txt_areaDisplay.setEditable(false);
        txt_areaDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_areaDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_areaDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        txt_areaDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_areaDisplayActionPerformed(evt);
            }
        });

        but_numTwo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numTwo.setText("2");
        but_numTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numTwoActionPerformed(evt);
            }
        });

        txt_numDisplay.setEditable(false);
        txt_numDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_numDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        txt_numDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numDisplayActionPerformed(evt);
            }
        });

        but_numThree.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numThree.setText("3");
        but_numThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numThreeActionPerformed(evt);
            }
        });

        but_numDecimal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numDecimal.setText(".");
        but_numDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numDecimalActionPerformed(evt);
            }
        });

        but_actPosNeg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_actPosNeg.setText("+/-");
        but_actPosNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_actPosNegActionPerformed(evt);
            }
        });

        but_numSeven.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numSeven.setText("7");
        but_numSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numSevenActionPerformed(evt);
            }
        });

        but_numEight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numEight.setText("8");
        but_numEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numEightActionPerformed(evt);
            }
        });

        but_numNine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numNine.setText("9");
        but_numNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numNineActionPerformed(evt);
            }
        });

        but_actDivide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_actDivide.setText("/");
        but_actDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_actDivideActionPerformed(evt);
            }
        });

        but_actMultiply.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_actMultiply.setText("*");
        but_actMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_actMultiplyActionPerformed(evt);
            }
        });

        but_actMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_actMinus.setText("-");
        but_actMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_actMinusActionPerformed(evt);
            }
        });

        but_actClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_actClear.setText("C");
        but_actClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_actClearActionPerformed(evt);
            }
        });

        but_numFour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_numFour.setText("4");
        but_numFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_numFourActionPerformed(evt);
            }
        });

        but_actEqual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_actEqual.setText("=");
        but_actEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_actEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(but_numSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_numFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_numOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(but_numEight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_numFive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_numTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(but_numSix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_numNine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_numThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but_actMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_actDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_actMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(but_actClear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(but_numZero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(but_numDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(but_actPosNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(but_actPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(but_actEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_areaDisplay)
                    .addComponent(txt_numDisplay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_areaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_numDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_numSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_numEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_numNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_actDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_numFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_numFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_numSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_actMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_numOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_numTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_numThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_actMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_numZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_numDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_actPosNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_actPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_actClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_actEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_numEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numEightActionPerformed
        setNumDisplay(but_numEight.getText());
    }//GEN-LAST:event_but_numEightActionPerformed

    private void but_numSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numSevenActionPerformed
        setNumDisplay(but_numSeven.getText());
    }//GEN-LAST:event_but_numSevenActionPerformed

    private void but_numNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numNineActionPerformed
        setNumDisplay(but_numNine.getText());
    }//GEN-LAST:event_but_numNineActionPerformed

    private void but_numFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numFourActionPerformed
        setNumDisplay(but_numFour.getText());
    }//GEN-LAST:event_but_numFourActionPerformed

    private void but_numOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numOneActionPerformed
        setNumDisplay(but_numOne.getText());
    }//GEN-LAST:event_but_numOneActionPerformed

    private void but_numZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numZeroActionPerformed
        setNumDisplay(but_numZero.getText());
    }//GEN-LAST:event_but_numZeroActionPerformed

    private void but_numFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numFiveActionPerformed
        setNumDisplay(but_numFive.getText());
    }//GEN-LAST:event_but_numFiveActionPerformed

    private void but_numTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numTwoActionPerformed
        setNumDisplay(but_numTwo.getText());
    }//GEN-LAST:event_but_numTwoActionPerformed

    private void but_numDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numDecimalActionPerformed
        setNumDisplay(but_numDecimal.getText());
    }//GEN-LAST:event_but_numDecimalActionPerformed

    private void but_numSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numSixActionPerformed
        setNumDisplay(but_numSix.getText());
    }//GEN-LAST:event_but_numSixActionPerformed

    private void but_numThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_numThreeActionPerformed
        setNumDisplay(but_numThree.getText());
    }//GEN-LAST:event_but_numThreeActionPerformed

    private void but_actPosNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_actPosNegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_actPosNegActionPerformed

    private void but_actClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_actClearActionPerformed
        clearCalcDisplay();
    }//GEN-LAST:event_but_actClearActionPerformed

    private void but_actDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_actDivideActionPerformed
        setCalcDisplay(" " + but_actDivide.getText() + " ");
    }//GEN-LAST:event_but_actDivideActionPerformed

    private void but_actMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_actMultiplyActionPerformed
        setCalcDisplay(" " + but_actMultiply.getText() + " ");
    }//GEN-LAST:event_but_actMultiplyActionPerformed

    private void but_actMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_actMinusActionPerformed
        setCalcDisplay(" " + but_actMinus.getText() + " ");
        performCalculation(but_actMinus.getText());
        txt_numDisplay.setText(decFormat.format(getPreviousVal()));        
    }//GEN-LAST:event_but_actMinusActionPerformed

    private void but_actPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_actPlusActionPerformed
        setCalcDisplay(" " + but_actPlus.getText() + " ");
        performCalculation(but_actPlus.getText());
        txt_numDisplay.setText(decFormat.format(getPreviousVal()));
    }//GEN-LAST:event_but_actPlusActionPerformed

    private void but_actEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_actEqualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_actEqualActionPerformed

    private void txt_areaDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_areaDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_areaDisplayActionPerformed

    private void txt_numDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numDisplayActionPerformed

    private void performCalculation(String sOperator){
        setActionTest(true);  
        double curVal = 0;
        switch (sOperator){
            case "+" :
                curVal = (getPreviousVal() + Double.parseDouble(txt_numDisplay.getText()));
                break;                
            case "-" :
                curVal = (getPreviousVal() - Double.parseDouble(txt_numDisplay.getText()));
                System.out.println("curVal is " + curVal);
                break;                
            case "*" :
                curVal = (Double.parseDouble(txt_numDisplay.getText()) * getPreviousVal());
                break;                
        }
        setPreviousVal(curVal);
        System.out.println("previousVal is " + getPreviousVal());     
    }
    
    private void setCalcDisplay(String dispVal){
        String enterNumber = txt_areaDisplay.getText() + txt_numDisplay.getText() + dispVal;
        txt_areaDisplay.setText(enterNumber);
    }
    
    private void setNumDisplay(String dispVal){
        String enterNumber;
        if(isActionTest() == true){
            enterNumber = "" + dispVal;
            setActionTest(false);
        }else{
            enterNumber = txt_numDisplay.getText() + dispVal;
        }
        txt_numDisplay.setText(enterNumber);
    }
    
    private void clearCalcDisplay(){
        String enterNumber = "";
        txt_numDisplay.setText(enterNumber);
        txt_areaDisplay.setText(enterNumber);
        setCurrentVal(0);
        setPreviousVal(0);
    }
    
    private String formatDoubleToString(double dispVal){
        String returnVal = decFormat.format(dispVal);
        return returnVal;
    }
        
    public boolean isActionTest(){
        return actionTest;
    }
    
    public void setActionTest (final boolean actionTest){
        this.actionTest = actionTest;
    }
    
    public double getPreviousVal(){
        return previousVal;
    }
    
    public void setPreviousVal(double previousVal){
        this.previousVal = previousVal;
    }
    
    public double getCurrentVal(){
        return currentVal;
    }
    
    public void setCurrentVal(double currentVal){
        this.currentVal = currentVal;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculators().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_actClear;
    private javax.swing.JButton but_actDivide;
    private javax.swing.JButton but_actEqual;
    private javax.swing.JButton but_actMinus;
    private javax.swing.JButton but_actMultiply;
    private javax.swing.JButton but_actPlus;
    private javax.swing.JButton but_actPosNeg;
    private javax.swing.JButton but_numDecimal;
    private javax.swing.JButton but_numEight;
    private javax.swing.JButton but_numFive;
    private javax.swing.JButton but_numFour;
    private javax.swing.JButton but_numNine;
    private javax.swing.JButton but_numOne;
    private javax.swing.JButton but_numSeven;
    private javax.swing.JButton but_numSix;
    private javax.swing.JButton but_numThree;
    private javax.swing.JButton but_numTwo;
    private javax.swing.JButton but_numZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_areaDisplay;
    private javax.swing.JTextField txt_numDisplay;
    // End of variables declaration//GEN-END:variables
}